### ISSUE TITLE
I try to run in the amazing docker image you have provided on my m1 Mac, but it says it does not support ARM64.

### ISSUE THREAD

**Issue by ghost** [igops/ngrok-skip-browser-warning#2]
Dear Igops,
Please help me igops, without your help I'll have no choice but to pay for ngrok premium. Please help me mate, I cannot run the image in the docker app on my M1 Mac mini, because it says the image does not support ARM64.
Kindest Regards,
GAMER.

![Screenshot 2023-04-02 at 10 35 23 am](https://user-images.githubusercontent.com/116552642/229324239-e03a4ca3-3e0c-4272-abc4-40d03c85d536.png)

![Screenshot 2023-04-02 at 10 35 28 am](https://user-images.githubusercontent.com/116552642/229324281-f236b03e-6dc2-439e-8849-fbaf3e3a6aee.png)

**Comment by igops** [comment]
Hi @GAMER12345678910214234234234234. Thank you for creating the issue!

Starting from July 9th, 2023 this image supports ARM chips. Please try downloading the latest version:
`$ docker pull igops/ngrok-skip-browser-warning:latest`
