### ISSUE TITLE
Using ngrok-skip-browser-warning from a different device on the same local LAN

### ISSUE THREAD

**Issue by OpherV** [igops/ngrok-skip-browser-warning#5]
Thanks for this package! It seems almost perfect for my needs.
Is there a way to use the proxy from different device on the local LAN?

My use-case is as follows:

- The platform I'm working on is a web server hosted online. Mobile browsers go to the URL where it's hosted and as part of the front end runtime it dynamically loads a JS module
- I'm developing this JS module, and I'd like to develop locally and test against the platform, so I'm using ngrok
- If I tell the platform to load the ngrok URL directly, it fails because ngrok returns the gate rather than the actual JS file. Since I'm testing on a mobile phone, I can't change the headers nor can I click their "proceed" button (I don't get it since I'm not loading directly from the ngrok tunnel, rather the browser loads a JS module from ngrok, expects a JS file but receives the HTML gate page instead)
- I'd like to use ngrok-skip-browser-warning as a local proxy on my dev machine, and then point the runtime to it, so the phone's browser will actually be able to load the JS module, and I could do my local development. 
- However this means I can't run it with localhost.direct (since the phone is a separate device from my development laptop)

**Comment by igops** [comment]
Hi @OpherV,

Recently, I created a similar setup using [Charles Proxy](https://www.charlesproxy.com).
If you start Charles on a computer where the _ngrok-skip-browser-warning_ (Device A) is running, and point your mobile phone in the same LAN to proxy everything through the local IP address of Device A, then everything should work right out of the box.

Please let me know, haven't I missed anything?

**Comment by OpherV** [comment]
I'll give it a shot, thanks!
